# Generated by Django 5.2.7 on 2026-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_announcement_created_by_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
